/**
 * Local copy of the skill catalog for seeding (db package does not depend on contracts).
 * Keep in sync with packages/contracts/src/skills-catalog.ts SKILL_CATALOG.
 */
export const SEED_SKILLS = [
  { key: "agriculture", name: "Agriculture", description: "Grow crops and manage farmland.", category: "agriculture" },
  { key: "animal_husbandry", name: "Animal husbandry", description: "Raise livestock and dairy.", category: "agriculture" },
  { key: "horticulture", name: "Horticulture", description: "Orchards, gardens, and specialty plants.", category: "agriculture" },
  { key: "viticulture", name: "Viticulture", description: "Grow grapes and make wine.", category: "agriculture" },
  { key: "beekeeping", name: "Beekeeping", description: "Keep bees and harvest honey.", category: "agriculture" },
  { key: "aquaculture", name: "Aquaculture", description: "Farm fish and shellfish.", category: "agriculture" },
  { key: "mining", name: "Mining", description: "Extract ore and stone from the earth.", category: "extraction" },
  { key: "forestry", name: "Forestry", description: "Fell timber and manage forests.", category: "extraction" },
  { key: "fishing", name: "Fishing", description: "Catch wild fish at sea or inland.", category: "extraction" },
  { key: "drilling", name: "Drilling", description: "Oil, gas, and deep-well operations.", category: "extraction" },
  { key: "prospecting", name: "Prospecting", description: "Find mineral and resource deposits.", category: "extraction" },
  { key: "manufacturing", name: "Manufacturing", description: "Run factories and assembly lines.", category: "crafts" },
  { key: "metallurgy", name: "Metallurgy", description: "Smelt and refine metals.", category: "crafts" },
  { key: "carpentry", name: "Carpentry", description: "Woodwork and fittings.", category: "crafts" },
  { key: "textiles", name: "Textiles", description: "Cloth, clothing, and fabric goods.", category: "crafts" },
  { key: "cooking", name: "Cooking", description: "Prepare food commercially.", category: "crafts" },
  { key: "brewing", name: "Brewing", description: "Brew beer and spirits.", category: "crafts" },
  { key: "crafts", name: "Crafts", description: "Handmade goods and artisanal work.", category: "crafts" },
  { key: "construction", name: "Construction", description: "Build structures and sites.", category: "construction" },
  { key: "engineering", name: "Engineering", description: "Design physical systems and infrastructure.", category: "construction" },
  { key: "architecture", name: "Architecture", description: "Design buildings and urban spaces.", category: "construction" },
  { key: "electrical", name: "Electrical", description: "Wiring, power, and electronics install.", category: "construction" },
  { key: "plumbing", name: "Plumbing", description: "Water and sanitation systems.", category: "construction" },
  { key: "programming", name: "Programming", description: "Software and computation.", category: "technology" },
  { key: "electronics", name: "Electronics", description: "Circuits and device hardware.", category: "technology" },
  { key: "robotics", name: "Robotics", description: "Automate machines and bots.", category: "technology" },
  { key: "data_analysis", name: "Data analysis", description: "Turn data into decisions.", category: "technology" },
  { key: "medicine", name: "Medicine", description: "Diagnose and treat illness.", category: "health" },
  { key: "nursing", name: "Nursing", description: "Patient care and clinical support.", category: "health" },
  { key: "pharmacy", name: "Pharmacy", description: "Compound and dispense medicines.", category: "health" },
  { key: "veterinary", name: "Veterinary", description: "Animal health and surgery.", category: "health" },
  { key: "management", name: "Management", description: "Organize people and work.", category: "services" },
  { key: "sales", name: "Sales", description: "Sell products and close deals.", category: "services" },
  { key: "hospitality", name: "Hospitality", description: "Hotels, tourism, and guest service.", category: "services" },
  { key: "teaching", name: "Teaching", description: "Educate others effectively.", category: "services" },
  { key: "journalism", name: "Journalism", description: "Investigate and publish news.", category: "social" },
  { key: "performing_arts", name: "Performing arts", description: "Music, theatre, and stage craft.", category: "social" },
  { key: "visual_arts", name: "Visual arts", description: "Painting, sculpture, and design.", category: "social" },
  { key: "security", name: "Security", description: "Protect people and property.", category: "security" },
  { key: "military", name: "Military", description: "Armed forces tactics and discipline.", category: "security" },
  { key: "logistics", name: "Logistics", description: "Move goods and people efficiently.", category: "transport" },
  { key: "piloting", name: "Piloting", description: "Fly aircraft (when aviation exists).", category: "transport" },
  { key: "seamanship", name: "Seamanship", description: "Operate ships and boats.", category: "transport" },
  { key: "driving", name: "Driving", description: "Operate road vehicles professionally.", category: "transport" },
  { key: "science", name: "Science", description: "Research and experimentation.", category: "science" },
  { key: "chemistry", name: "Chemistry", description: "Chemical processes and labs.", category: "science" },
  { key: "geology", name: "Geology", description: "Earth science and surveying.", category: "science" },
  { key: "law", name: "Law", description: "Legal reasoning and procedure.", category: "governance" },
  { key: "economics", name: "Economics", description: "Markets, trade, and finance.", category: "governance" },
  { key: "politics", name: "Politics", description: "Public office and coalition building.", category: "governance" },
  { key: "accounting", name: "Accounting", description: "Books, audits, and tax.", category: "governance" },
] as const;
